import "../../css/Projects.css";
import { RevealOnScroll } from "../RevealOnScroll";

export const Projects = () => {
  const projectData = [
    {
      title: "Digital Transformation Project on Service to Armed Forces",
      description:
        "Implemented a service support and tracking system through Salesforce Service Cloud for a leading non-profit organization in the US, providing emergency communication and financial assistance to armed forces personnel and their families. Led test design and execution, participated in discovery and story refinement, and tracked defects using JIRA, while coordinating with clients and preparing reports.",
      tech: ["JIRA", "Salesforce"],
    },
    {
      title: "Hotel/Resort Activity Management Portal",
      description:
        "Developed a portal to manage resort bookings and stay for guests and club members, ensuring a safe resort experience. Led sprint activities as Scrum Master, participated in Scrum events, coordinated with developers, product owners, and business users, and performed testing using Postman and Saucelabs for APIs.",
      tech: ["ServiceNow", "SauceLabs", "Salesforce", "Mulesoft", "PEGA"],
    },
    {
      title: "IIB Migration to MuleSoft",
      description:
        "Migrated an insurance company's integration platform from IIB to Mulesoft AnyPoint, migrating 150 APIs. Conducted extensive testing, created test strategies, and tracked testing reports using Postman and SOAP UI.",
      tech: ["JIRA", "Mulesoft"],
    },
    {
      title: "APIC_DP Migration to Mulesoft",
      description:
        "Migrated from API Connect (APIC) and DataPower (DP) to Mulesoft AnyPoint for an insurance company, ensuring 100 APIs were migrated successfully with rigorous testing, test strategy, and reporting.",
      tech: ["JIRA", "Mulesoft"],
    },
    {
      title: "Blood Drive Management System",
      description:
        "Developed a Blood Drive Management System for a biomedical services organization, including designing test cases and executing them to ensure proper functionality.",
      tech: ["JIRA", "Salesforce"],
    },
    {
      title: "Lead Management System in PEGA",
      description:
        "Created a Lead Management System using PEGA that captured leads generated by marketing agents. Designed and executed test cases, built a Maven-based testing framework, and led test execution for the project.",
      tech: ["JIRA", "PEGA"],
    },
    {
      title: "Business Portal Implementation for SAHAJ e-Village Ltd",
      description:
        "Developed an online portal for various transactions like insurance products, government identity cards, and other services. Led testing, documentation of use cases, and coordination with cross-functional teams.",
      tech: ["Mantis", "JAVA", "MySQL"],
    },
    {
      title: "Business Postal Server Migration to Cloud",
      description:
        "Led the migration of a business portal from an in-house data center to an AWS cloud environment. Documented test scenarios, led execution, and obtained final sign-off for the testing phase.",
      tech: ["Mantis", "JAVA", "MySQL", "AWS Cloud"],
    },
    {
      title: "Financial Services Insurance Product Implementation",
      description:
        "Developed a system for users to select and apply for insurance products online. Gathered requirements, prepared test cases, and executed scripts to ensure defect-free deployment.",
      tech: ["Mantis", "JAVA", "MySQL"],
    },
    {
      title: "Mobile Applications at WebSpiders",
      description:
        "Developed mobile applications for a retail customer, handling marketing and campaign activities with both web-based and PDA components. Created test plans, executed test cases, and ensured end-to-end coverage.",
      tech: ["JIRA", "JAVA", "ASP.NET", "PDA (Windows Mobile)"],
    },
    {
      title: "Car Volume Communication Project at WebSpiders",
      description:
        "Developed a web-based application to forecast part manufacturing based on distributor sales figures. Led the test team, created test plans, executed tests, and obtained sign-off for the project.",
      tech: ["JIRA", "ASP.NET"],
    },
    {
      title: "Car Configurator Project at WebSpiders",
      description:
        "Developed a car configurator application for Mitsubishi to allow buyers to customize cars. Led the test team, created test plans, and ensured comprehensive testing coverage.",
      tech: ["JIRA", "ASP.NET"],
    },
  ];

  return (
    <section id="projects" className="projects-section">
      <RevealOnScroll>
        <div className="projects-container">
          <h2 className="projects-title">Featured Projects</h2>
          <div className="projects-grid">
            {projectData.map((project, index) => (
              <div key={index} className="project-card">
                <h3 className="project-title">{project.title}</h3>
                <p className="project-desc">{project.description}</p>
                <div className="project-tech">
                  {project.tech.map((tech, idx) => (
                    <span key={idx} className="tech-badge">
                      {tech}
                    </span>
                  ))}
                </div>
                {/* <a
                  href={project.link}
                  className="project-link"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  View Project →
                </a> */}
              </div>
            ))}
          </div>
        </div>
      </RevealOnScroll>
    </section>
  );
};
